# Generated by Django 5.1.8 on 2025-06-11 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=50)),
                ('service_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=50)),
                ('pwd', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='sub_services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subservice_name', models.CharField(max_length=100)),
                ('subservice_id', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elder_services.services')),
            ],
        ),
        migrations.CreateModel(
            name='bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_time', models.DateTimeField()),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('price', models.CharField(max_length=50)),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elder_services.services')),
                ('subservice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elder_services.sub_services')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elder_services.user_info')),
            ],
        ),
    ]
